[package]
name = "yoteoke"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.15"
bevy_egui = "0.31"
egui_file = "0.19"
serde = "1.0.216"
serde_json = "1.0.133"
kira = { version = "0.9.6", features = ["symphonia"] }
regex = "1.11.1"